#!/bin/bash

INTERFACE="wlo1"
SSID="CAPTIVE_PORTAL"
GATEWAY="10.0.0.1"

if [[ ${EUID} != 0 ]]; then
    echo "This program must be run as root."
    exit 1
fi

echo "Stopping NetworkManager..."
systemctl stop NetworkManager

echo "Starting AP..."
create_ap \
    -g "${GATEWAY}" \
    --no-virt \
    --redirect-to-localhost \
    --logfile "${PWD}/create_ap.log" \
    --dns-logfile "${PWD}/dnsmasq.log" \
    --daemon \
    -n "${INTERFACE}" "${SSID}"

sleep 2

echo "Starting HTTP server..."
python main.py "${GATEWAY}" 80

echo "Exiting, please wait..."

echo "Stopping processes..."
pkill create_ap

sleep 5

echo "Restarting NetworkManager..."
systemctl start NetworkManager
